apiVersion: v1
kind: Secret
metadata:
  name: icow-s3-access
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  accesskey: {{ .Values.s3.access_key | toString | b64enc | quote }}
  secretkey: {{ .Values.s3.secret_key | toString | b64enc | quote }}
